CREATE TABLE slugs
(
  id    SERIAL PRIMARY KEY,
  title TEXT   NOT NULL UNIQUE
);

CREATE TABLE users
(
  id BIGINT PRIMARY KEY 
);

CREATE TABLE slugs_users
(
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE ON UPDATE NO ACTION,
  slug_id INTEGER REFERENCES slugs (id) ON DELETE CASCADE ON UPDATE NO ACTION,
  PRIMARY KEY (user_id, slug_id)
);